"use client";

import Head from 'next/head'
import React , { useState } from 'react'
import Image from 'next/image'
import Link from 'next/link'

import { ImQuotesLeft, ImQuotesRight } from "react-icons/im"

import Carousel from 'react-multi-carousel';
import 'react-multi-carousel/lib/styles.css';

import CategoryCard from '../Rent/CategoryCard';

import HeroImage from "../../public/assets/Home/hero-image.jpg"

// men
import MenFormal from "../../public/assets/Home/men-formal.jpg"
import MenCasual from "../../public/assets/Home/men-casual.jpg"
import MenTraditional from "../../public/assets/Home/men-traditional.jpg"

// women
import WomenFormal from "../../public/assets/Home/women-formal.jpg"
import WomenCasual from "../../public/assets/Home/women-casual.jpg"
import WomenTraditional from "../../public/assets/Home/women-traditional.jpg"
import WomenDresses from "../../public/assets/Home/women-dress.jpg"

// bestsellers
// men
import OffWhiteSherwani from "../../public/assets/Rent/Rent-Main/Men/Traditional/off-white-sherwani.png"
import BlackSuit from "../../public/assets/Rent/Rent-Main/Men/Formal/suits/black-checked-suit.png"
import KhaakiPants from "../../public/assets/Rent/Rent-Main/Men/Casual/bottoms/khaki-cargo-pants.png"
import PurpleKurta from "../../public/assets/Rent/Rent-Main/Men/Traditional/purple-kurta-set.png"
import TealBlazer from "../../public/assets/Rent/Rent-Main/Men/Formal/blazers/teal-blazer.png"
import MarvelSweatShirt from "../../public/assets/Rent/Rent-Main/Men/Casual/tshirts/marvel-sweatshirt.png"

// women
import PinkSilkLehenga from "../../public/assets/Rent/Rent-Main/Women/traditional/deep-pink-silk-lehenga.png"
import GreenKSaree from "../../public/assets/Rent/Rent-Main/Women/traditional/sea-green-traditional-kanjeevaram-saree.png"
import PinkBlazer from '../../public/assets/Rent/Rent-Main/Women/formal/pink-fitted-blazer.png'
import BlackPartyDress from "../../public/assets/Rent/Rent-Main/Women/dresses/black-and-silver-party-dress.png"
import GreenJumpsuit from "../../public/assets/Rent/Rent-Main/Women/dresses/solid-green-casual-jumpsuit.png"
import BlueDungaree from "../../public/assets/Rent/Rent-Main/Women/casual/blue-denim-dungaree.png"

// customers
import EmilyCooper from "../../public/assets/Home/emily.png"
import Gabriel from "../../public/assets/Home/gabriel.png"
import Alfie from "../../public/assets/Home/alfie.png"
import MindyChen from "../../public/assets/Home/ashley.jpg"
import Camille from "../../public/assets/Home/camille.jpg"
import Sylvie from "../../public/assets/Home/sylvie.jpeg"


import { BsArrowUpRight } from 'react-icons/bs'

import Navbar from "../Navbar"
import Footer from '../Footer'

function Homepage() {

  const [option, setOption] = useState(false)
  
  const responsive = {
    superLargeDesktop: {
      // the naming can be any, depends on you.
      breakpoint: { max: 4000, min: 1440},
      items: 3
    },
    desktop: {
      breakpoint: { max: 3000, min: 1024 },
      items: 2  
    },
    tablet: {
      breakpoint: { max: 1024, min: 767 },
      items: 2
    },
    mobile: {
      breakpoint: { max: 768, min: 0 },
      items: 1
    }
  };

  return (
    <>
      <Navbar />
      <div className='font-Playfair md:pt-24'>
        {/* HERO */}
        <div className='relative text-center'> 
          <Image src={HeroImage} alt="Hero-image" className='h-[26rem] w-full'/>
          <div className='absolute top-[50%] left-[50%] -translate-x-2/4 -translate-y-2/4 typewriter'>
            <p className='font-bold text-3xl md:text-5xl bg-black/90 text-white w-fit p-1 main'>Ramp Ready</p>
            <p className='font-semibold text-xl md:text-2xl bg-black/90 text-white w-fit p-1 subtitle'>Making fashion Sustainable.</p>
          </div>
          <Link href="/rent">
            <div className='absolute top-[86%] left-[50%] -translate-x-2/4 -translate-y-2/4 flex flex-row gap-x-2 bg-black text-white p-2 hover:scale-105 hover:border text-md md:text-xl'>
              <button className=''>
                Start Renting
              </button>
              <BsArrowUpRight className='my-auto mx-auto'/>
            </div>
          </Link>
        </div>


        {/* About Us */}
        <div className='my-20 mx-10 md:m-20 text-xl'>
          <p className='font-bold text-2xl md:text-4xl w-[50%] text-center mx-auto'>Our mission is to power people to feel their best every day.</p>
          <p className='pt-5 text-center md:text-left'>
            The amount of waste that is generated by the Fashion industry poses a huge risk for the future generations. We&apos;re sure that you have some clothes inside your closet that are untouched or maybe used for an occasion or two. Inorder to stop you from buying clothes that cannot be worn for other occasions, you can choose the rental option given by our website to make you look fabulous for your next event and that too in a budget!
          </p>
          <p className='pt-5 text-center md:text-left'>
            Ramp Ready was introduced to help people feel amazing and put together while expressing themselves in the clothing of thier choice without having to think about any monetory issues. 
          </p>
        </div>

        <div className='bg-black h-[0.5px] w-full'></div>

        {/* Categories */}
        <div className='my-20 mx-20'>
          <p className='font-bold text-center text-3xl md:text-4xl'>Choose from a variety of categories for:</p>
          
          <p className='font-bold text-center text-xl md:text-3xl mt-10'>MEN</p>
          <div className='grid grid-cols-1 md:grid-cols-2 gap-14 place-items-center'>
            {/* Formal */}
            <div class="flip-card mt-10 w-[220px] h-[300px] md:w-[320px] md:h-[400px]">
              <div class="flip-card-inner">
                <div class="flip-card-front">
                  <h1 className='absolute top-[50%] left-[50%] -translate-x-2/4 -translate-y-2/4 text-2xl md:text-4xl font-bold'>Formal Wear</h1> 
                </div>
                <div class="flip-card-back">
                  <Image src={MenFormal} alt="Men-formals" className='w-[220px] h-[300px] md:w-[350px] md:h-[400px]'/>
                  <Link href="/men">
                    <div className='absolute top-[86%] left-[50%] -translate-x-2/4 -translate-y-2/4 flex flex-row gap-x-2 bg-black text-white p-2 hover:scale-105 hover:border text-xl'>
                      <button className=''>
                        Rent
                      </button>
                      <BsArrowUpRight className='my-auto mx-auto'/>
                    </div>
                  </Link>
                </div>
              </div>
            </div>

            {/* Casual */}
            <div class="flip-card w-[220px] h-[300px] md:w-[320px] md:h-[400px] mt-10">
              <div class="flip-card-inner">
                <div class="flip-card-front">
                  <h1 className='absolute top-[50%] left-[50%] -translate-x-2/4 -translate-y-2/4 text-2xl md:text-4xl font-bold '>Casual Wear</h1> 
                </div>
                <div class="flip-card-back">
                  <Image src={MenCasual} alt="Men-formals" className='w-[220px] h-[300px] md:w-[350px] md:h-[400px]'/>
                  <Link href="/men">
                    <div className='absolute top-[86%] left-[50%] -translate-x-2/4 -translate-y-2/4 flex flex-row gap-x-2 bg-black text-white p-2 hover:scale-105 hover:border text-xl'>
                      <button className=''>
                        Rent
                      </button>
                      <BsArrowUpRight className='my-auto mx-auto'/>
                    </div>
                  </Link>
                </div>
              </div>
            </div>

            {/* Traditional */}
            <div class="flip-card w-[220px] h-[300px] md:w-[320px] md:h-[400px] mt-6">
              <div class="flip-card-inner">
                <div class="flip-card-front">
                  <h1 className='absolute top-[50%] left-[50%] -translate-x-2/4 -translate-y-2/4 text-2xl md:text-4xl font-bold'>Traditional Wear</h1> 
                </div>
                <div class="flip-card-back">
                  <Image src={MenTraditional} alt="Men-formals" className='w-[220px] h-[300px] md:w-[350px] md:h-[400px]'/>
                  <Link href="/men">
                    <div className='absolute top-[86%] left-[50%] -translate-x-2/4 -translate-y-2/4 flex flex-row gap-x-2 bg-black text-white p-2 hover:scale-105 hover:border text-xl'>
                      <button className=''>
                        Rent
                      </button>
                      <BsArrowUpRight className='my-auto mx-auto'/>
                    </div>
                  </Link>
                </div>
              </div>
            </div>
          </div>

          <p className='font-bold text-center text-xl md:text-3xl mt-10'>WOMEN</p>
          <div className='grid grid-cols-1 md:grid-cols-2 gap-14 place-items-center'>
            {/* Formal */}
            <div class="flip-card w-[220px] h-[300px] md:w-[320px] md:h-[400px] mt-10">
              <div class="flip-card-inner">
                <div class="flip-card-front">
                  <h1 className='absolute top-[50%] left-[50%] -translate-x-2/4 -translate-y-2/4 text-2xl md:text-4xl font-bold'>Formal Wear</h1> 
                </div>
                <div class="flip-card-back">
                  <Image src={WomenFormal} alt="Men-formals" className='w-[220px] h-[300px] md:w-[350px] md:h-[400px]'/>
                  <Link href="/women">
                    <div className='absolute top-[86%] left-[50%] -translate-x-2/4 -translate-y-2/4 flex flex-row gap-x-2 bg-black text-white p-2 hover:scale-105 hover:border text-xl'>
                      <button className=''>
                        Rent
                      </button>
                      <BsArrowUpRight className='my-auto mx-auto'/>
                    </div>
                  </Link>
                </div>
              </div>
            </div>

            {/* Casual */}
            <div class="flip-card w-[220px] h-[300px] md:w-[320px] md:h-[400px] mt-10">
              <div class="flip-card-inner">
                <div class="flip-card-front">
                  <h1 className='absolute top-[50%] left-[50%] -translate-x-2/4 -translate-y-2/4 text-2xl md:text-4xl font-bold'>Casual Wear</h1> 
                </div>
                <div class="flip-card-back">
                  <Image src={WomenCasual} alt="Men-formals" className='w-[220px] h-[300px] md:w-[350px] md:h-[400px]'/>
                  <Link href="/women">
                    <div className='absolute top-[86%] left-[50%] -translate-x-2/4 -translate-y-2/4 flex flex-row gap-x-2 bg-black text-white p-2 hover:scale-105 hover:border text-xl'>
                      <button className=''>
                        Rent
                      </button>
                      <BsArrowUpRight className='my-auto mx-auto'/>
                    </div>
                  </Link>
                </div>
              </div>
            </div>

            {/* Traditional */}
            <div class="flip-card w-[220px] h-[300px] md:w-[320px] md:h-[400px] mt-6">
              <div class="flip-card-inner">
                <div class="flip-card-front">
                  <h1 className='absolute top-[50%] left-[50%] -translate-x-2/4 -translate-y-2/4 text-2xl md:text-4xl font-bold'>Traditional Wear</h1> 
                </div>
                <div class="flip-card-back">
                  <Image src={WomenTraditional} alt="Men-formals" className='w-[220px] h-[300px] md:w-[350px] md:h-[400px]'/>
                  <Link href="/women">
                    <div className='absolute top-[86%] left-[50%] -translate-x-2/4 -translate-y-2/4 flex flex-row gap-x-2 bg-black text-white p-2 hover:scale-105 hover:border text-xl'>
                      <button className=''>
                        Rent
                      </button>
                      <BsArrowUpRight className='my-auto mx-auto'/>
                    </div>
                  </Link>
                </div>
              </div>
            </div>

            {/* Dresses */}
            <div class="flip-card w-[220px] h-[300px] md:w-[320px] md:h-[400px] mt-6">
              <div class="flip-card-inner">
                <div class="flip-card-front">
                  <h1 className='absolute top-[50%] left-[50%] -translate-x-2/4 -translate-y-2/4 text-2xl md:text-4xl font-bold'>Dresses</h1> 
                </div>
                <div class="flip-card-back">
                  <Image src={WomenDresses} alt="Men-formals" className='w-[220px] h-[300px] md:w-[350px] md:h-[400px]'/>
                  <Link href="/women">
                    <div className='absolute top-[86%] left-[50%] -translate-x-2/4 -translate-y-2/4 flex flex-row gap-x-2 bg-black text-white p-2 hover:scale-105 hover:border text-xl'>
                      <button className=''>
                        Rent
                      </button>
                      <BsArrowUpRight className='my-auto mx-auto'/>
                    </div>
                  </Link>
                </div>
              </div>
            </div>
          </div>
          
        </div>
        
        <div className='bg-black h-[0.5px] w-full'></div>

        {/* Our Bestsellers */}
        <div className='m-20'>
          <p className='font-bold text-center text-3xl md:text-4xl'>
            Our Bestsellers
          </p>

          <div className='flex flex-row gap-x-20 py-5 justify-center text-2xl'>
            <p className={`cursor-pointer menu-links ${option ? "no-underline" : "underline decoration-beige underline-offset-8"}`} onClick={() => setOption(false)}>Men</p>
            <p onClick={() => setOption(true)} className={`cursor-pointer menu-links ${option ? "underline decoration-beige underline-offset-8" : "no-underline"}`}>Women {option}</p>
          </div>

          {option ? 
            <div className='grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-10 md:mx-20 mt-8'>
              <CategoryCard
                image={PinkSilkLehenga}
                brand="Manish Malhotra"
                product="Pink Silk Lehenga"
                price="INR 850"
              />
              <CategoryCard
                image={GreenKSaree}
                brand="Chennai Silks"
                product="Green Kanjeevaram Saree"
                price="INR 980"
              />
              <CategoryCard
                image={PinkBlazer}
                brand="Van Heusen"
                product="Pink Blazer"
                price="INR 400"
              />
              <CategoryCard
                image={BlackPartyDress}
                brand="Zara"
                product="Black Party Dress"
                price="INR 420"
              />
              <CategoryCard
                image={GreenJumpsuit}
                brand="Myntra"
                product="Green Jumpsuit"
                price="INR 370"
              />
              <CategoryCard
                image={BlueDungaree}
                brand="Zara"
                product="Blue Dungaree"
                price="INR 480"
              />
            </div>
          : 
            <div className='grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-10 md:mx-20 mt-8'>
            <CategoryCard
              image={BlackSuit}
              brand="Van Heusen"
              product="Black Striped Suit"
              price="INR 440"
            />
            <CategoryCard
              image={KhaakiPants}
              brand="Peter England"
              product="Khaaki Cargo Pants"
              price="INR 500"
            />
            <CategoryCard
              image={PurpleKurta}
              brand="Flying Machine"
              product="Beige cargo Pants"
              price="INR 300"
            />
            <CategoryCard
              image={OffWhiteSherwani}
              brand="FabIndia"
              product="Off White Sherwani"
              price="INR 750"
            />
            <CategoryCard
              image={MarvelSweatShirt}
              brand="Bewakoof"
              product="Marvel Sweatshirt"
              price="INR 500"
            />
            <CategoryCard
              image={TealBlazer}
              brand="Peter England"
              product="Teal Blazer"
              price="INR 500"
            />
            </div>
          }
        </div>

        <div className='bg-black h-[0.5px] w-full'></div>
        {/* What People Say About us */}
        <div className='my-20 mx-7 md:m-20'>
          <p className='text-3xl md:text-4xl font-bold text-center'>What our customers say about us</p>
          <Carousel responsive={responsive}>
            {/* Emily Cooper */}
            <div className='border border-white h-[30rem] w-[14rem] md:h-[25rem] md:w-[20rem] p-10 my-20 bg-beige shadow-lg shadow-beige'>
              <Image src={EmilyCooper} alt="arya-pic" className='w-24 rounded-full mx-auto border border-white border-2'/>
              <p className='font-bold text-xl text-center py-5 text-white'>Emily Cooper</p>
              <ImQuotesLeft className='text-white text-xl mx-auto'/>
              <p className='text-white text-center pt-1'>It is a wonderful website to rent clothes with reasonable prices. I have rented clothes for several occasions and they are worth thier price!</p>
              <ImQuotesRight className='text-white pt-1 text-2xl mx-auto'/>
            </div>

            {/* Gabriel */}
            <div className='border border-white h-[30rem] w-[14rem] md:h-[25rem] md:w-[20rem] p-10 my-20 bg-beige shadow-lg shadow-beige'>
              <Image src={Gabriel} alt="arya-pic" className='w-24 rounded-full mx-auto border border-white border-2'/>
              <p className='font-bold text-xl text-center py-5 text-white'>Gabriel</p>
              <ImQuotesLeft className='text-white text-xl mx-auto'/>
              <p className='text-white text-center pt-1'>It is a has a diverse range of products to choose from and the procedure is also hassle-free. I am a very frequent rentee of Ramp Ready.</p>
              <ImQuotesRight className='text-white pt-1 text-2xl mx-auto'/>
            </div>

            {/* Alfie */}
            <div className='border border-white h-[30rem] w-[14rem] md:h-[25rem] md:w-[20rem] p-10 my-20 bg-beige shadow-lg shadow-beige'>
              <Image src={Alfie} alt="arya-pic" className='w-24 rounded-full mx-auto border border-white border-2'/>
              <p className='font-bold text-xl text-center py-5 text-white'>Alfie</p>
              <ImQuotesLeft className='text-white text-xl mx-auto'/>
              <p className='text-white text-center pt-1'>I have rented clothes for different occasions and I am very happy with the service. The products are of high quality and classy at the same time!</p>
              <ImQuotesRight className='text-white pt-1 text-2xl mx-auto'/>
            </div>

            {/* Camille */}
            <div className='border border-white h-[30rem] w-[14rem] md:h-[25rem] md:w-[20rem] p-10 my-20 bg-beige shadow-lg shadow-beige'>
              <Image src={Camille} alt="arya-pic" className='w-24 rounded-full mx-auto border border-white border-2'/>
              <p className='font-bold text-xl text-center py-5 text-white'>Camille</p>
              <ImQuotesLeft className='text-white text-xl mx-auto'/>
              <p className='text-white text-center pt-1'>Ramp Ready has saved me thousands of dollars and invaluable time.I no longer have to worry about what I&apos;m going to wear.</p>
              <ImQuotesRight className='text-white pt-1 text-2xl mx-auto'/>
            </div>

            {/* Mindy Chen */}
            <div className='border border-white h-[30rem] w-[14rem] md:h-[25rem] md:w-[20rem] p-10 my-20 bg-beige shadow-lg shadow-beige'>
              <Image src={MindyChen} alt="arya-pic" className='w-24 rounded-full mx-auto border border-white border-2'/>
              <p className='font-bold text-xl text-center py-5 text-white'>Mindy Chen</p>
              <ImQuotesLeft className='text-white text-xl mx-auto'/>
              <p className='text-white text-center pt-1'>I feel more confident now through the way I dress, and I feel great that I&apos;m making a sustainable choice each time I rent.</p>
              <ImQuotesRight className='text-white pt-1 text-2xl mx-auto'/>
            </div>

            {/* Sylvie */}
            <div className='border border-white h-[30rem] w-[14rem] md:h-[25rem] md:w-[20rem] p-10 my-20 bg-beige shadow-lg shadow-beige'>
              <Image src={Sylvie} alt="arya-pic" className='w-24 rounded-full mx-auto border border-white border-2'/>
              <p className='font-bold text-xl text-center py-5 text-white'>Sylvie</p>
              <ImQuotesLeft className='text-white text-xl mx-auto'/>
              <p className='text-white text-center pt-1'>I get to wear top designers every day! I always imagined I could live this life, but now it&apos;s a reality.</p>
              <ImQuotesRight className='text-white pt-1 text-2xl mx-auto'/>
            </div>
          </Carousel>
        </div>

        <div className='bg-black h-[0.5px] w-full'></div>

        {/* Contact */}
        <div className='m-20 text-3xl md:text-4xl text-center'>
          <p>Have any further questions?</p>
          <Link href="/contact" className='hover:font-bold'>
            <p className='menu-links mt-5 md:mt-0'>Contact Us!</p>
          </Link> 
        </div>
      </div>
      <Footer/>
    </>
  )
}

export default Homepage