"use client";

import Head from 'next/head'
import React , { useState } from 'react'
import Image from 'next/image'
import Link from 'next/link'

import CategoryCard from '../Rent/CategoryCard';

import HeroImage from "../../public/assets/Home/hero-image.jpg"

// men
import MenFormal from "../../public/assets/Home/men-formal.jpg"
import MenCasual from "../../public/assets/Home/men-casual.jpg"
import MenTraditional from "../../public/assets/Home/men-traditional.jpg"

// women
import WomenFormal from "../../public/assets/Home/women-formal.jpg"
import WomenCasual from "../../public/assets/Home/women-casual.jpg"
import WomenTraditional from "../../public/assets/Home/women-traditional.jpg"
import WomenDresses from "../../public/assets/Home/women-dress.jpg"

// bestsellers
// men
import OffWhiteSherwani from "../../public/assets/Rent/Rent-Main/Men/Traditional/off-white-sherwani.png"
import BlackSuit from "../../public/assets/Rent/Rent-Main/Men/Formal/suits/black-checked-suit.png"
import KhaakiPants from "../../public/assets/Rent/Rent-Main/Men/Casual/bottoms/khaki-cargo-pants.png"
import PurpleKurta from "../../public/assets/Rent/Rent-Main/Men/Traditional/purple-kurta-set.png"
import TealBlazer from "../../public/assets/Rent/Rent-Main/Men/Formal/blazers/teal-blazer.png"
import MarvelSweatShirt from "../../public/assets/Rent/Rent-Main/Men/Casual/tshirts/marvel-sweatshirt.png"

// women
import PinkSilkLehenga from "../../public/assets/Rent/Rent-Main/Women/traditional/deep-pink-silk-lehenga.png"
import GreenKSaree from "../../public/assets/Rent/Rent-Main/Women/traditional/sea-green-traditional-kanjeevaram-saree.png"
import PinkBlazer from '../../public/assets/Rent/Rent-Main/Women/formal/pink-fitted-blazer.png'
import BlackPartyDress from "../../public/assets/Rent/Rent-Main/Women/dresses/black-and-silver-party-dress.png"
import GreenJumpsuit from "../../public/assets/Rent/Rent-Main/Women/dresses/solid-green-casual-jumpsuit.png"
import BlueDungaree from "../../public/assets/Rent/Rent-Main/Women/casual/blue-denim-dungaree.png"


import { BsArrowUpRight } from 'react-icons/bs'

import Navbar from "../Navbar"
import Footer from '../Footer'

function Homepage() {

  const [option, setOption] = useState(false)

  return (
    <>
      <Navbar />
      <div className='font-Playfair pt-24'>
        {/* HERO */}
        <div className='relative text-center'> 
          <Image src={HeroImage} alt="Hero-image" className='h-[26rem] w-full'/>
          <div className='absolute top-[50%] left-[50%] -translate-x-2/4 -translate-y-2/4 typewriter'>
            <p className='font-bold text-5xl bg-black/90 text-white w-fit p-1 main'>Ramp Ready</p>
            <p className='font-semibold text-2xl bg-black/90 text-white w-fit p-1 subtitle'>Making fashion Sustainable.</p>
          </div>
          <Link href="/rent">
            <div className='absolute top-[86%] left-[50%] -translate-x-2/4 -translate-y-2/4 flex flex-row gap-x-2 bg-black text-white p-2 hover:scale-105 hover:border text-xl'>
              <button className=''>
                Start Renting
              </button>
              <BsArrowUpRight className='my-auto mx-auto'/>
            </div>
          </Link>
        </div>


        {/* About Us */}
        <div className='m-20 text-xl'>
          <p className='font-bold text-4xl w-[50%] text-center mx-auto'>Our mission is to power people to feel their best every day.</p>
          <p className='pt-5'>
            The amount of waste that is generated by the Fashion industry poses a huge risk for the future generations. We&apos;re sure that you have some clothes inside your closet that are untouched or maybe used for an occasion or two. Inorder to stop you from buying clothes that cannot be worn for other occasions, you can choose the rental option given by our website to make you look fabulous for your next event and that too in a budget!
          </p>
          <p className='pt-5'>
            Ramp Ready was introduced to help people feel amazing and put together while expressing themselves in the clothing of thier choice without having to think about any monetory issues. 
          </p>
        </div>

        <div className='bg-black h-[0.5px] w-full'></div>

        {/* Categories */}
        <div className='my-20 mx-20'>
          <p className='font-bold text-center text-4xl'>Choose from a variety of categories for:</p>
          
          <p className='font-bold text-center text-3xl mt-10'>MEN</p>
          <div className='grid grid-cols-2 gap-14 place-items-center'>
            {/* Formal */}
            <div class="flip-card mt-10">
              <div class="flip-card-inner">
                <div class="flip-card-front">
                  <h1 className='absolute top-[50%] left-[50%] -translate-x-2/4 -translate-y-2/4 text-4xl font-bold'>Formal Wear</h1> 
                </div>
                <div class="flip-card-back">
                  <Image src={MenFormal} alt="Men-formals" className='w-[350px] h-[400px]'/>
                  <Link href="/men">
                    <div className='absolute top-[86%] left-[50%] -translate-x-2/4 -translate-y-2/4 flex flex-row gap-x-2 bg-black text-white p-2 hover:scale-105 hover:border text-xl'>
                      <button className=''>
                        Rent
                      </button>
                      <BsArrowUpRight className='my-auto mx-auto'/>
                    </div>
                  </Link>
                </div>
              </div>
            </div>

            {/* Casual */}
            <div class="flip-card mt-10">
              <div class="flip-card-inner">
                <div class="flip-card-front">
                  <h1 className='absolute top-[50%] left-[50%] -translate-x-2/4 -translate-y-2/4 text-4xl font-bold'>Casual Wear</h1> 
                </div>
                <div class="flip-card-back">
                  <Image src={MenCasual} alt="Men-formals" className='w-[350px] h-[400px]'/>
                  <Link href="/men">
                    <div className='absolute top-[86%] left-[50%] -translate-x-2/4 -translate-y-2/4 flex flex-row gap-x-2 bg-black text-white p-2 hover:scale-105 hover:border text-xl'>
                      <button className=''>
                        Rent
                      </button>
                      <BsArrowUpRight className='my-auto mx-auto'/>
                    </div>
                  </Link>
                </div>
              </div>
            </div>

            {/* Traditional */}
            <div class="flip-card mt-6">
              <div class="flip-card-inner">
                <div class="flip-card-front">
                  <h1 className='absolute top-[50%] left-[50%] -translate-x-2/4 -translate-y-2/4 text-4xl font-bold'>Traditional Wear</h1> 
                </div>
                <div class="flip-card-back">
                  <Image src={MenTraditional} alt="Men-formals" className='w-[350px] h-[400px]'/>
                  <Link href="/men">
                    <div className='absolute top-[86%] left-[50%] -translate-x-2/4 -translate-y-2/4 flex flex-row gap-x-2 bg-black text-white p-2 hover:scale-105 hover:border text-xl'>
                      <button className=''>
                        Rent
                      </button>
                      <BsArrowUpRight className='my-auto mx-auto'/>
                    </div>
                  </Link>
                </div>
              </div>
            </div>
          </div>

          <p className='font-bold text-center text-3xl mt-10'>WOMEN</p>
          <div className='grid grid-cols-2 gap-14 place-items-center'>
            {/* Formal */}
            <div class="flip-card mt-10">
              <div class="flip-card-inner">
                <div class="flip-card-front">
                  <h1 className='absolute top-[50%] left-[50%] -translate-x-2/4 -translate-y-2/4 text-4xl font-bold'>Formal Wear</h1> 
                </div>
                <div class="flip-card-back">
                  <Image src={WomenFormal} alt="Men-formals" className='w-[350px] h-[400px]'/>
                  <Link href="/women">
                    <div className='absolute top-[86%] left-[50%] -translate-x-2/4 -translate-y-2/4 flex flex-row gap-x-2 bg-black text-white p-2 hover:scale-105 hover:border text-xl'>
                      <button className=''>
                        Rent
                      </button>
                      <BsArrowUpRight className='my-auto mx-auto'/>
                    </div>
                  </Link>
                </div>
              </div>
            </div>

            {/* Casual */}
            <div class="flip-card mt-10">
              <div class="flip-card-inner">
                <div class="flip-card-front">
                  <h1 className='absolute top-[50%] left-[50%] -translate-x-2/4 -translate-y-2/4 text-4xl font-bold'>Casual Wear</h1> 
                </div>
                <div class="flip-card-back">
                  <Image src={WomenCasual} alt="Men-formals" className='w-[350px] h-[400px]'/>
                  <Link href="/women">
                    <div className='absolute top-[86%] left-[50%] -translate-x-2/4 -translate-y-2/4 flex flex-row gap-x-2 bg-black text-white p-2 hover:scale-105 hover:border text-xl'>
                      <button className=''>
                        Rent
                      </button>
                      <BsArrowUpRight className='my-auto mx-auto'/>
                    </div>
                  </Link>
                </div>
              </div>
            </div>

            {/* Traditional */}
            <div class="flip-card mt-6">
              <div class="flip-card-inner">
                <div class="flip-card-front">
                  <h1 className='absolute top-[50%] left-[50%] -translate-x-2/4 -translate-y-2/4 text-4xl font-bold'>Traditional Wear</h1> 
                </div>
                <div class="flip-card-back">
                  <Image src={WomenTraditional} alt="Men-formals" className='w-[350px] h-[400px]'/>
                  <Link href="/women">
                    <div className='absolute top-[86%] left-[50%] -translate-x-2/4 -translate-y-2/4 flex flex-row gap-x-2 bg-black text-white p-2 hover:scale-105 hover:border text-xl'>
                      <button className=''>
                        Rent
                      </button>
                      <BsArrowUpRight className='my-auto mx-auto'/>
                    </div>
                  </Link>
                </div>
              </div>
            </div>

            {/* Dresses */}
            <div class="flip-card mt-6">
              <div class="flip-card-inner">
                <div class="flip-card-front">
                  <h1 className='absolute top-[50%] left-[50%] -translate-x-2/4 -translate-y-2/4 text-4xl font-bold'>Dresses</h1> 
                </div>
                <div class="flip-card-back">
                  <Image src={WomenDresses} alt="Men-formals" className='w-[350px] h-[400px]'/>
                  <Link href="/women">
                    <div className='absolute top-[86%] left-[50%] -translate-x-2/4 -translate-y-2/4 flex flex-row gap-x-2 bg-black text-white p-2 hover:scale-105 hover:border text-xl'>
                      <button className=''>
                        Rent
                      </button>
                      <BsArrowUpRight className='my-auto mx-auto'/>
                    </div>
                  </Link>
                </div>
              </div>
            </div>
          </div>
          
        </div>
        
        <div className='bg-black h-[0.5px] w-full'></div>

        {/* Our Bestsellers */}
        <div className='m-20'>
          <p className='font-bold text-center text-4xl'>
            Our Bestsellers
          </p>

          <div className='flex flex-row gap-x-20 py-5 justify-center text-2xl'>
            <p className='cursor-pointer' onClick={() => setOption(false)}>Men</p>
            <p className='cursor-pointer' onClick={() => setOption(true)}>Women</p>
          </div>

          {option ? 
            <div className='grid grid-cols-3 gap-10 mx-20 mt-8'>
              <CategoryCard
                image={PinkSilkLehenga}
                brand="Manish Malhotra"
                product="Pink Silk Lehenga"
                price="INR 850"
              />
              <CategoryCard
                image={GreenKSaree}
                brand="Chennai Silks"
                product="Green Kanjeevaram Saree"
                price="INR 980"
              />
              <CategoryCard
                image={PinkBlazer}
                brand="Van Heusen"
                product="Pink Blazer"
                price="INR 400"
              />
              <CategoryCard
                image={BlackPartyDress}
                brand="Zara"
                product="Black Party Dress"
                price="INR 420"
              />
              <CategoryCard
                image={GreenJumpsuit}
                brand="Myntra"
                product="Green Jumpsuit"
                price="INR 370"
              />
              <CategoryCard
                image={BlueDungaree}
                brand="Zara"
                product="Blue Dungaree"
                price="INR 480"
              />
            </div>
          : 
            <div className='grid grid-cols-3 gap-10 mx-20 mt-8'>
            <CategoryCard
              image={BlackSuit}
              brand="Van Heusen"
              product="Black Striped Suit"
              price="INR 440"
            />
            <CategoryCard
              image={KhaakiPants}
              brand="Peter England"
              product="Khaaki Cargo Pants"
              price="INR 500"
            />
            <CategoryCard
              image={PurpleKurta}
              brand="Flying Machine"
              product="Beige cargo Pants"
              price="INR 300"
            />
            <CategoryCard
              image={OffWhiteSherwani}
              brand="FabIndia"
              product="Off White Sherwani"
              price="INR 750"
            />
            <CategoryCard
              image={MarvelSweatShirt}
              brand="Bewakoof"
              product="Marvel Sweatshirt"
              price="INR 500"
            />
            <CategoryCard
              image={TealBlazer}
              brand="Peter England"
              product="Teal Blazer"
              price="INR 500"
            />
            </div>
          }
        </div>

        <div className='bg-black h-[0.5px] w-full'></div>
        {/* What People Say About us */}
        <div className='m-20'>
          <p className='text-4xl font-bold text-center'>What Customers say about us</p>

        </div>

        <div className='bg-black h-[0.5px] w-full'></div>

        {/* Contact */}
        <div className='m-20 text-4xl text-center'>
          <p>Have any further questions?</p>
          <Link href="/contact" className='hover:font-bold'>
            <p className='menu-links'>Contact Us!</p>
          </Link> 
        </div>
      </div>
      <Footer/>
    </>
  )
}

export default Homepage